# Copyright (C) 2021, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

cukinia_log "$(_colorize yellow "--- Check inactive partition symlinks ---")"
SYMLINK_ROOTFS="/dev/upgradable_rootfs"
UPGRADABLE_ROOTFS=$(readlink -f $SYMLINK_ROOTFS 2>/dev/null || true)

id "SEAPATH-00116" as "$SYMLINK_ROOTFS exists" cukinia_test -L "$SYMLINK_ROOTFS"
id "SEAPATH-00118" as "$SYMLINK_ROOTFS points to inactive bank" \
    cukinia_test "$(/usr/share/update/is_from_inactive_bank.sh rootfs $UPGRADABLE_ROOTFS)" \
    == "1"
